nodes:
    dataset:
        unique_property: name
        other_properties:
            - description
    term:
        unique_property: name
        other_properties:
            - definition
            - source_system
            - possible_values
            - notes
            - data_sensitivity
            - data_availability
    office:
        unique_property: name
    report:
        unique_property: name
        other_properties:
            - datasource
            - data_last_updated 
            - description
            - tableau_link
            - report_type
            - thumbnail_uri
    domain_tag:
        unique_property: name
    bus_process_tag:
        unique_property: name
    security_role:
        unique_property: name
        other_properties: 
            - role_eds_code
            - is_public
            - is_admin
            - create_access_to
            - read_access_to
            - update_access_to
            - delete_access_to
            - report_role
            - iam_export_code
    user:
        unique_property: net_id
relationships:
    HAS_DOMAIN_TAG:
        source_label: report
        target_label: domain_tag
    HAS_BUSPROCESS_TAG:
        source_label: report
        target_label: bus_process_tag
    HAS_STAKE_IN:
        source_label: office
        name_to_source: stakes
        target_label: term
        name_to_target: stakeholders
        properties:
            - stake
    IS_MADE_WITH:
        target_label: dataset
        source_label: report
    IS_OWNED_BY:
        target_label: office
        source_label: 
            - report
            - dataset
        properties:
            - stake   
    CONTAINS:
        target_label: term
        source_label: 
            - report
            - dataset
    ALLOWS_ACCESS_WITH:
        target_label: security_role
        source_label:
            - report
            - term
            - dataset
        name_to_source: allows_access_with
        properties:
            - allow_update_and_delete
    HAS_ROLE:
        source_label: user
        target_label: security_role
    IS_FAVORITE_OF:
        source_label: report
        name_to_source: users_favoring
        target_label: user
        name_to_target: favorites