nodes:
    term:
        unique_property: name
        other_properties:
            - definition
            - source_system
            - possible_values
            - notes
            - data_sensitivity
            - data_availability
    office:
        unique_property: name
    report:
        unique_property: name
        other_properties:
            - datasource
            - data_last_updated 
            - description
            - embedJSON              
            - report_type
            - thumbnail_uri
    domain_tag:
        unique_property: name
    bus_process_tag:
      unique_property: name
    security_role:
        unique_property: name
        other_properties: 
            - role_eds_code
            - is_public
            - report_role
relationships:
    HAS_DOMAIN_TAG:
        source_label: report
        target_label: domain_tag
    HAS_BUSPROCESS_TAG:
        source_label: report
        target_label: bus_process_tag
    HAS_STAKE_IN:
        source_label: office
        name_to_source: stakes
        target_label: term
        name_to_target: stakeholders
        properties:
            - stake
    IS_OWNED_BY:
        source_label: report
        target_label: office
    CONTAINS:
        source_label: report
        target_label: term
    REQUIRES:
        source_label: report
        target_label: security_role