nodes:
    term:
        unique_property: name
        other_properties:
            - definition
            - source_system
            - possible_values
            - notes
            - data_sensitivity
            - data_availability
    office:
        unique_property: name
    user:
        unique_property: net_id
        other_properties:
            - first_name
            - last_name
    report:
        unique_property: name
        other_properties:
            - uri
            - description
    security_role:
        unique_property: name
        other_properties:
            - is_public
    security_regime:
        unique_property: name
        other_properties:
            - integrated_with_portal
relationships:
    HAS_STAKE_IN:
        source_label: office
        name_to_source: stakes
        target_label: term
        name_to_target: stakeholders
        properties:
            - stake
    CONTAINS:
        source_label: report
        target_label: term
    REPRESENTS_FOR:
        source_label: user
        target_label: office
    CAN_VIEW:
        source_label: security_role
        target_label: report
    IS_FROM:
        source_label: security_role
        target_label: security_regime
        target_number: one
    HAS_ROLE:
        source_label: user
        target_label: security_role
